from          = "From:" (mailbox-list / address-list) CRLF
sender        = "Sender:" (mailbox / address) CRLF
reply-to      = "Reply-To:" address-list CRLF
resent-from   = "Resent-From:" (mailbox-list / address-list) CRLF
resent-sender = "Resent-Sender:" (mailbox / address) CRLF
